export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_INITIAL_MESSAGES = 'GET_INITIAL_MESSAGES';
export const SORT_MESSAGES = 'SORT_MESSAGES';

export const SET_REQUEST_SETTINGS = 'SET_REQUEST_SETTINGS';
export const SET_LOADING_END = 'LOADING_END'
export const SET_LAST_MESSAGE_ID = 'SET_LAST_MESSAGE_ID';
export const SET_LIST_ORDER = 'SET_LIST_ORDER';

export const REQUEST = '_REQUEST';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';